#!/bin/sh

#script to easily change between dual displays
#1: laptop display (LVDS only)
#2: dual screen (VGA and LVDS)
#3: only VGA


if [ "$1" = "1" ]; then
    xrandr --auto --output LVDS1 --mode 1366x768
    xrandr --output HDMI1 --off
elif [ "$1" = "2" ]; then
    xrandr
    xrandr --auto --output HDMI1 --mode 1360x768
    xrandr --output LVDS1 --off
elif [ "$1" = "3" ]; then
    xrandr
    xrandr --auto --output HDMI1 --mode 1360x768 --left-of LVDS1 --primary 
elif [ "$1" = "4" ]; then
    xrandr
    xrandr --auto --output HDMI1 --mode 1920x1080 --left-of LVDS1 --primary
elif [ "$1" = "5" ]; then
    xrandr
    xrandr --auto --output HDMI1 --mode 1920x1080
    xrandr --output LVDS1 --off
else
    echo "need parameter: 1=laptop, 2= dual, 3=tv"
fi
