code --install-extension adam-bender.commit-message-editor
code --install-extension adammaras.overtype
code --install-extension alefragnani.Bookmarks
code --install-extension bierner.markdown-mermaid
code --install-extension blackblackcat.silver-gray
code --install-extension eamodio.gitlens
code --install-extension fabiospampinato.vscode-highlight
code --install-extension jdinhlife.gruvbox
code --install-extension karyfoundation.theme-karyfoundation-themes
code --install-extension kopub.pydocstring
code --install-extension magicstack.MagicPython
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ptweir.python-string-sql
code --install-extension Shan.code-settings-sync
code --install-extension yzhang.markdown-all-in-one
